#!/bin/sh

nvim -u NONE -c 'set rtp^=$PWD ignorecase | call colortemplate#make(".", "!", 0) | qall!' \
    -- templates/suisei.colortemplate && \

rm -rf ./artwork && rm -rf ./autoload && rm -rf ./templates && \
sed -i bak 's/^colors\///g; s/^doc\///g' .gitignore && rm .gitignorebak
