" Name:         「水星」
" Version:      0.0.1
" Author:       Orchx <suisei@47.rs>
" Maintainer:   Orchx <suisei@47.rs>
" URL:          https://github.com/theme-suisei/Suisei.vim
" Website:      https://suisei.journal.md
" License:      MIT
" Last Updated: Wed Apr 22 16:20:52 2020

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'suisei'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#1D242d', '#908f95', '#344457', '#546478',
          \ '#6aa389', '#6cad89', '#435c8a', '#4d75bd', '#ad8a5e', '#d4a56c',
          \ '#68678a', '#7d7bad', '#916e6e', '#bf7c7c', '#995665', '#c76d81']
    if has('nvim')
      let g:terminal_color_0 = '#1D242d'
      let g:terminal_color_1 = '#908f95'
      let g:terminal_color_2 = '#344457'
      let g:terminal_color_3 = '#546478'
      let g:terminal_color_4 = '#6aa389'
      let g:terminal_color_5 = '#6cad89'
      let g:terminal_color_6 = '#435c8a'
      let g:terminal_color_7 = '#4d75bd'
      let g:terminal_color_8 = '#ad8a5e'
      let g:terminal_color_9 = '#d4a56c'
      let g:terminal_color_10 = '#68678a'
      let g:terminal_color_11 = '#7d7bad'
      let g:terminal_color_12 = '#916e6e'
      let g:terminal_color_13 = '#bf7c7c'
      let g:terminal_color_14 = '#995665'
      let g:terminal_color_15 = '#c76d81'
    endif
    if get(g:, 'suisei_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=#908f95 guibg=NONE guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#908f95 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#908f95 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#908f95 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    endif
    hi ColorColumn guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi Conceal guisp=NONE gui=NONE cterm=NONE
    hi Cursor guibg=#908f95 guisp=NONE gui=NONE cterm=NONE
    hi CursorColumn guifg=#908f95 guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guibg=#353f4d guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#ad8a5e guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=#6aa389 guisp=NONE gui=NONE cterm=NONE
    hi DiffChange guifg=#ad8a5e guisp=NONE gui=NONE cterm=NONE
    hi DiffDelete guifg=#995665 guisp=NONE gui=NONE cterm=NONE
    hi DiffText guifg=#908f95 guisp=NONE gui=NONE cterm=NONE
    hi Directory guifg=#546478 guisp=NONE gui=NONE cterm=NONE
    if get(g:, 'suisei_hide_end_of_buffer', 0)
      hi EndOfBuffer guifg=#1D242d guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    else
      hi EndOfBuffer guifg=#242b34 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    endif
    hi ErrorMsg guifg=#c76d81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#353f4d guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#546478 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    hi IncSearch guisp=NONE gui=standout cterm=standout
    hi LineNr guifg=#353f4d guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi MatchParen guibg=NONE guisp=NONE gui=underline cterm=underline
    hi ModeMsg guifg=#908f95 guisp=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#908f95 guisp=NONE gui=NONE cterm=NONE
    hi NonText guifg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=#908f95 guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#908f95 guibg=#353f4d guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guibg=#344457 guisp=NONE gui=NONE cterm=NONE
    hi Question guifg=#908f95 guisp=NONE gui=NONE cterm=NONE
    hi Search guifg=#908f95 guibg=#353f4d guisp=NONE gui=NONE cterm=NONE
    hi SignColumn guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#242b34 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    hi Whitespace guifg=#242b34 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=#c76d81 guisp=NONE gui=underline cterm=underline
    hi SpellCap guifg=#bf7c7c guisp=NONE gui=underline cterm=underline
    hi SpellLocal guifg=#7d7bad guisp=NONE gui=underline cterm=underline
    hi SpellRare guifg=#546478 guisp=NONE gui=underline cterm=underline
    if get(g:, 'suisei_hide_statusline', 0)
      hi StatusLine guifg=#908f95 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
      hi StatusLineNC guifg=#908f95 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    else
      hi StatusLine guifg=#1D242d guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
      hi StatusLineNC guifg=#1D242d guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    endif
    hi TabLine guifg=#908f95 guibg=#1D242d guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=#908f95 guibg=#353f4d guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#908f95 guisp=NONE gui=NONE cterm=NONE
    if get(g:, 'suisei_hide_vert_split', 0)
      hi VertSplit guifg=NONE guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    else
      hi VertSplit guifg=#1D242d guibg=NONE guisp=NONE gui=NONE cterm=NONE
    endif
    hi Visual guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi VisualNOS guibg=#995665 guisp=NONE gui=NONE cterm=NONE
    hi WarningMsg guifg=#d4a56c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi WildMenu guifg=#908f95 guibg=#242b34 guisp=NONE gui=NONE cterm=NONE
    hi Comment guifg=#546478 guisp=NONE gui=italic cterm=italic
    hi Constant guifg=#7d7bad guisp=NONE gui=NONE cterm=NONE
    hi String guifg=#6aa389 guisp=NONE gui=NONE cterm=NONE
    hi Error guifg=#c76d81 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Identifier guifg=#bf7c7c guisp=NONE gui=NONE cterm=NONE
    hi Ignore guifg=#344457 guisp=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#546478 guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#7d7bad guisp=NONE gui=NONE cterm=NONE
    hi Statement guifg=#4d75bd guisp=NONE gui=NONE cterm=NONE
    hi Todo guifg=#6aa389 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Type guifg=#4d75bd guisp=NONE gui=italic cterm=italic
    hi Underlined guifg=#435c8a guisp=NONE gui=underline cterm=underline
    hi haskellDecl guifg=#d4a56c guisp=NONE gui=NONE cterm=NONE
    hi haskellType guifg=#7d7bad guisp=NONE gui=NONE cterm=NONE
    hi haskellPragma guifg=#d4a56c guisp=NONE gui=NONE cterm=NONE
    hi rustCommentLineDoc guifg=#344457 guisp=NONE gui=NONE cterm=NONE
    hi rustAttribute guifg=#ad8a5e guisp=NONE gui=NONE cterm=NONE
    hi rustDerive guifg=#ad8a5e guisp=NONE gui=NONE cterm=NONE
    hi rustLifetime guifg=#bf7c7c guisp=NONE gui=NONE cterm=NONE
    hi rustSelf guifg=#bf7c7c guisp=NONE gui=NONE cterm=NONE
    hi rustUnsafeKeyword guifg=#995665 guisp=NONE gui=NONE cterm=NONE
    hi mkdHeading guifg=#ad8a5e guisp=NONE gui=NONE cterm=NONE
    hi mkdCode guifg=#7d7bad guisp=NONE gui=NONE cterm=NONE
    hi GitGutterAdd guifg=#6aa389 guisp=NONE gui=NONE cterm=NONE
    hi GitGutterChange guifg=#ad8a5e guisp=NONE gui=NONE cterm=NONE
    hi GitGutterDelete guifg=#995665 guisp=NONE gui=NONE cterm=NONE
    hi GitGutterChangeDelete guifg=#916e6e guisp=NONE gui=NONE cterm=NONE
    hi NERDTreeCWD guifg=#344457 guisp=NONE gui=NONE cterm=NONE
    hi NERDTreeExecFile guifg=#435c8a guisp=NONE gui=NONE cterm=NONE
    hi NERDTreeOpenable guifg=#344457 guisp=NONE gui=NONE cterm=NONE
    hi NERDTreeClosable guifg=#546478 guisp=NONE gui=NONE cterm=NONE
    hi NERDTreeFile guifg=#546478 guisp=NONE gui=NONE cterm=NONE
    hi NERDTreeDir guifg=#546478 guisp=NONE gui=NONE cterm=NONE
    hi NERDTreeDirSlash guifg=#546478 guisp=NONE gui=NONE cterm=NONE
    hi SignatureMarkText guifg=#7d7bad guisp=NONE gui=NONE cterm=NONE
    if !s:italics
      hi Comment gui=NONE cterm=NONE
      hi Type gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#F0F0F4', '#102C4E', '#676880', '#A0A0AD',
        \ '#718A7D', '#5E8D89', '#3C5685', '#4969A3', '#BA8F4C', '#D9A250',
        \ '#565163', '#7C758F', '#634F4F', '#A17F7F', '#995757', '#C47474']
  if has('nvim')
    let g:terminal_color_0 = '#F0F0F4'
    let g:terminal_color_1 = '#102C4E'
    let g:terminal_color_2 = '#676880'
    let g:terminal_color_3 = '#A0A0AD'
    let g:terminal_color_4 = '#718A7D'
    let g:terminal_color_5 = '#5E8D89'
    let g:terminal_color_6 = '#3C5685'
    let g:terminal_color_7 = '#4969A3'
    let g:terminal_color_8 = '#BA8F4C'
    let g:terminal_color_9 = '#D9A250'
    let g:terminal_color_10 = '#565163'
    let g:terminal_color_11 = '#7C758F'
    let g:terminal_color_12 = '#634F4F'
    let g:terminal_color_13 = '#A17F7F'
    let g:terminal_color_14 = '#995757'
    let g:terminal_color_15 = '#C47474'
  endif
  if get(g:, 'suisei_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#102C4E guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#102C4E guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#102C4E guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#102C4E guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guisp=NONE gui=NONE cterm=NONE
  hi Cursor guibg=#102C4E guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=#102C4E guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guibg=#D2D2D9 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#BA8F4C guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#718A7D guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#BA8F4C guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#995757 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#102C4E guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#A0A0AD guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'suisei_hide_end_of_buffer', 0)
    hi EndOfBuffer guifg=#F0F0F4 guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  else
    hi EndOfBuffer guifg=#E4E4E8 guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ErrorMsg guifg=#C47474 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#D2D2D9 guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#A0A0AD guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#D2D2D9 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ModeMsg guifg=#102C4E guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#102C4E guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#102C4E guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#102C4E guibg=#D2D2D9 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guibg=#676880 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#102C4E guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#102C4E guibg=#D2D2D9 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#E4E4E8 guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  hi Whitespace guifg=#E4E4E8 guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#C47474 guisp=NONE gui=underline cterm=underline
  hi SpellCap guifg=#A17F7F guisp=NONE gui=underline cterm=underline
  hi SpellLocal guifg=#7C758F guisp=NONE gui=underline cterm=underline
  hi SpellRare guifg=#A0A0AD guisp=NONE gui=underline cterm=underline
  if get(g:, 'suisei_hide_statusline', 0)
    hi StatusLine guifg=#102C4E guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#102C4E guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  else
    hi StatusLine guifg=#F0F0F4 guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#F0F0F4 guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  endif
  hi TabLine guifg=#102C4E guibg=#F0F0F4 guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#102C4E guibg=#D2D2D9 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#102C4E guisp=NONE gui=NONE cterm=NONE
  if get(g:, 'suisei_hide_vert_split', 0)
    hi VertSplit guifg=NONE guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  else
    hi VertSplit guifg=#F0F0F4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  endif
  hi Visual guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guibg=#995757 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#D9A250 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#102C4E guibg=#E4E4E8 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#A0A0AD guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#7C758F guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#718A7D guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#C47474 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#A17F7F guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#676880 guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#A0A0AD guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#7C758F guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#4969A3 guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#718A7D guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#4969A3 guisp=NONE gui=italic cterm=italic
  hi Underlined guifg=#3C5685 guisp=NONE gui=underline cterm=underline
  hi haskellDecl guifg=#D9A250 guisp=NONE gui=NONE cterm=NONE
  hi haskellType guifg=#7C758F guisp=NONE gui=NONE cterm=NONE
  hi haskellPragma guifg=#D9A250 guisp=NONE gui=NONE cterm=NONE
  hi rustCommentLineDoc guifg=#676880 guisp=NONE gui=NONE cterm=NONE
  hi rustAttribute guifg=#BA8F4C guisp=NONE gui=NONE cterm=NONE
  hi rustDerive guifg=#BA8F4C guisp=NONE gui=NONE cterm=NONE
  hi rustLifetime guifg=#A17F7F guisp=NONE gui=NONE cterm=NONE
  hi rustSelf guifg=#A17F7F guisp=NONE gui=NONE cterm=NONE
  hi rustUnsafeKeyword guifg=#995757 guisp=NONE gui=NONE cterm=NONE
  hi mkdHeading guifg=#BA8F4C guisp=NONE gui=NONE cterm=NONE
  hi mkdCode guifg=#7C758F guisp=NONE gui=NONE cterm=NONE
  hi GitGutterAdd guifg=#718A7D guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChange guifg=#BA8F4C guisp=NONE gui=NONE cterm=NONE
  hi GitGutterDelete guifg=#995757 guisp=NONE gui=NONE cterm=NONE
  hi GitGutterChangeDelete guifg=#634F4F guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeCWD guifg=#676880 guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeExecFile guifg=#3C5685 guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeOpenable guifg=#676880 guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeClosable guifg=#A0A0AD guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeFile guifg=#A0A0AD guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeDir guifg=#A0A0AD guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeDirSlash guifg=#A0A0AD guisp=NONE gui=NONE cterm=NONE
  hi SignatureMarkText guifg=#7C758F guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi Type gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'suisei_transp_bg', 0) && !has('gui_running')
      hi Normal ctermfg=246 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=246 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=246 ctermbg=235 cterm=NONE
      if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
        set background=dark
      endif
      hi Terminal ctermfg=246 ctermbg=235 cterm=NONE
    endif
    hi ColorColumn ctermbg=235 cterm=NONE
    hi Conceal cterm=NONE
    hi Cursor ctermbg=246 cterm=NONE
    hi CursorColumn ctermfg=246 ctermbg=235 cterm=NONE
    hi CursorLine ctermbg=237 cterm=NONE
    hi CursorLineNr ctermfg=137 ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=72 cterm=NONE
    hi DiffChange ctermfg=137 cterm=NONE
    hi DiffDelete ctermfg=95 cterm=NONE
    hi DiffText ctermfg=246 cterm=NONE
    hi Directory ctermfg=241 cterm=NONE
    if get(g:, 'suisei_hide_end_of_buffer', 0)
      hi EndOfBuffer ctermfg=235 ctermbg=235 cterm=NONE
    else
      hi EndOfBuffer ctermfg=235 ctermbg=235 cterm=NONE
    endif
    hi ErrorMsg ctermfg=168 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=237 ctermbg=235 cterm=NONE
    hi Folded ctermfg=241 ctermbg=235 cterm=NONE
    hi IncSearch cterm=reverse
    hi LineNr ctermfg=237 ctermbg=NONE cterm=NONE
    hi MatchParen ctermbg=NONE cterm=underline
    hi ModeMsg ctermfg=246 cterm=NONE
    hi MoreMsg ctermfg=246 cterm=NONE
    hi NonText ctermfg=235 cterm=NONE
    hi Pmenu ctermfg=246 ctermbg=235 cterm=NONE
    hi PmenuSbar ctermbg=235 cterm=NONE
    hi PmenuSel ctermfg=246 ctermbg=237 cterm=NONE
    hi PmenuThumb ctermbg=238 cterm=NONE
    hi Question ctermfg=246 cterm=NONE
    hi Search ctermfg=246 ctermbg=237 cterm=NONE
    hi SignColumn ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=235 ctermbg=235 cterm=NONE
    hi Whitespace ctermfg=235 ctermbg=235 cterm=NONE
    hi SpellBad ctermfg=168 cterm=underline
    hi SpellCap ctermfg=174 cterm=underline
    hi SpellLocal ctermfg=103 cterm=underline
    hi SpellRare ctermfg=241 cterm=underline
    if get(g:, 'suisei_hide_statusline', 0)
      hi StatusLine ctermfg=246 ctermbg=235 cterm=NONE
      hi StatusLineNC ctermfg=246 ctermbg=235 cterm=NONE
    else
      hi StatusLine ctermfg=235 ctermbg=235 cterm=NONE
      hi StatusLineNC ctermfg=235 ctermbg=235 cterm=NONE
    endif
    hi TabLine ctermfg=246 ctermbg=235 cterm=NONE
    hi TabLineFill ctermbg=235 cterm=NONE
    hi TabLineSel ctermfg=246 ctermbg=237 cterm=NONE
    hi Title ctermfg=246 cterm=NONE
    if get(g:, 'suisei_hide_vert_split', 0)
      hi VertSplit ctermfg=NONE ctermbg=235 cterm=NONE
    else
      hi VertSplit ctermfg=235 ctermbg=NONE cterm=NONE
    endif
    hi Visual ctermbg=235 cterm=NONE
    hi VisualNOS ctermbg=95 cterm=NONE
    hi WarningMsg ctermfg=180 ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=246 ctermbg=235 cterm=NONE
    hi Comment ctermfg=241 cterm=italic
    hi Constant ctermfg=103 cterm=NONE
    hi String ctermfg=72 cterm=NONE
    hi Error ctermfg=168 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=174 cterm=NONE
    hi Ignore ctermfg=238 cterm=NONE
    hi PreProc ctermfg=241 cterm=NONE
    hi Special ctermfg=103 cterm=NONE
    hi Statement ctermfg=68 cterm=NONE
    hi Todo ctermfg=72 ctermbg=NONE cterm=NONE
    hi Type ctermfg=68 cterm=italic
    hi Underlined ctermfg=60 cterm=underline
    hi haskellDecl ctermfg=180 cterm=NONE
    hi haskellType ctermfg=103 cterm=NONE
    hi haskellPragma ctermfg=180 cterm=NONE
    hi rustCommentLineDoc ctermfg=238 cterm=NONE
    hi rustAttribute ctermfg=137 cterm=NONE
    hi rustDerive ctermfg=137 cterm=NONE
    hi rustLifetime ctermfg=174 cterm=NONE
    hi rustSelf ctermfg=174 cterm=NONE
    hi rustUnsafeKeyword ctermfg=95 cterm=NONE
    hi mkdHeading ctermfg=137 cterm=NONE
    hi mkdCode ctermfg=103 cterm=NONE
    hi GitGutterAdd ctermfg=72 cterm=NONE
    hi GitGutterChange ctermfg=137 cterm=NONE
    hi GitGutterDelete ctermfg=95 cterm=NONE
    hi GitGutterChangeDelete ctermfg=95 cterm=NONE
    hi NERDTreeCWD ctermfg=238 cterm=NONE
    hi NERDTreeExecFile ctermfg=60 cterm=NONE
    hi NERDTreeOpenable ctermfg=238 cterm=NONE
    hi NERDTreeClosable ctermfg=241 cterm=NONE
    hi NERDTreeFile ctermfg=241 cterm=NONE
    hi NERDTreeDir ctermfg=241 cterm=NONE
    hi NERDTreeDirSlash ctermfg=241 cterm=NONE
    hi SignatureMarkText ctermfg=103 cterm=NONE
    if !s:italics
      hi Comment cterm=NONE
      hi Type cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'suisei_transp_bg', 0) && !has('gui_running')
    hi Normal ctermfg=236 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=236 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=236 ctermbg=255 cterm=NONE
    hi Terminal ctermfg=236 ctermbg=255 cterm=NONE
  endif
  hi ColorColumn ctermbg=254 cterm=NONE
  hi Conceal cterm=NONE
  hi Cursor ctermbg=236 cterm=NONE
  hi CursorColumn ctermfg=236 ctermbg=254 cterm=NONE
  hi CursorLine ctermbg=252 cterm=NONE
  hi CursorLineNr ctermfg=137 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=66 cterm=NONE
  hi DiffChange ctermfg=137 cterm=NONE
  hi DiffDelete ctermfg=131 cterm=NONE
  hi DiffText ctermfg=236 cterm=NONE
  hi Directory ctermfg=247 cterm=NONE
  if get(g:, 'suisei_hide_end_of_buffer', 0)
    hi EndOfBuffer ctermfg=255 ctermbg=255 cterm=NONE
  else
    hi EndOfBuffer ctermfg=254 ctermbg=255 cterm=NONE
  endif
  hi ErrorMsg ctermfg=174 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=252 ctermbg=255 cterm=NONE
  hi Folded ctermfg=247 ctermbg=255 cterm=NONE
  hi IncSearch cterm=reverse
  hi LineNr ctermfg=252 ctermbg=NONE cterm=NONE
  hi MatchParen ctermbg=NONE cterm=underline
  hi ModeMsg ctermfg=236 cterm=NONE
  hi MoreMsg ctermfg=236 cterm=NONE
  hi NonText ctermfg=254 cterm=NONE
  hi Pmenu ctermfg=236 ctermbg=254 cterm=NONE
  hi PmenuSbar ctermbg=254 cterm=NONE
  hi PmenuSel ctermfg=236 ctermbg=252 cterm=NONE
  hi PmenuThumb ctermbg=60 cterm=NONE
  hi Question ctermfg=236 cterm=NONE
  hi Search ctermfg=236 ctermbg=252 cterm=NONE
  hi SignColumn ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=254 ctermbg=255 cterm=NONE
  hi Whitespace ctermfg=254 ctermbg=255 cterm=NONE
  hi SpellBad ctermfg=174 cterm=underline
  hi SpellCap ctermfg=138 cterm=underline
  hi SpellLocal ctermfg=103 cterm=underline
  hi SpellRare ctermfg=247 cterm=underline
  if get(g:, 'suisei_hide_statusline', 0)
    hi StatusLine ctermfg=236 ctermbg=255 cterm=NONE
    hi StatusLineNC ctermfg=236 ctermbg=255 cterm=NONE
  else
    hi StatusLine ctermfg=255 ctermbg=255 cterm=NONE
    hi StatusLineNC ctermfg=255 ctermbg=255 cterm=NONE
  endif
  hi TabLine ctermfg=236 ctermbg=255 cterm=NONE
  hi TabLineFill ctermbg=254 cterm=NONE
  hi TabLineSel ctermfg=236 ctermbg=252 cterm=NONE
  hi Title ctermfg=236 cterm=NONE
  if get(g:, 'suisei_hide_vert_split', 0)
    hi VertSplit ctermfg=NONE ctermbg=254 cterm=NONE
  else
    hi VertSplit ctermfg=255 ctermbg=NONE cterm=NONE
  endif
  hi Visual ctermbg=254 cterm=NONE
  hi VisualNOS ctermbg=131 cterm=NONE
  hi WarningMsg ctermfg=179 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=236 ctermbg=254 cterm=NONE
  hi Comment ctermfg=247 cterm=italic
  hi Constant ctermfg=103 cterm=NONE
  hi String ctermfg=66 cterm=NONE
  hi Error ctermfg=174 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=138 cterm=NONE
  hi Ignore ctermfg=60 cterm=NONE
  hi PreProc ctermfg=247 cterm=NONE
  hi Special ctermfg=103 cterm=NONE
  hi Statement ctermfg=25 cterm=NONE
  hi Todo ctermfg=66 ctermbg=NONE cterm=NONE
  hi Type ctermfg=25 cterm=italic
  hi Underlined ctermfg=60 cterm=underline
  hi haskellDecl ctermfg=179 cterm=NONE
  hi haskellType ctermfg=103 cterm=NONE
  hi haskellPragma ctermfg=179 cterm=NONE
  hi rustCommentLineDoc ctermfg=60 cterm=NONE
  hi rustAttribute ctermfg=137 cterm=NONE
  hi rustDerive ctermfg=137 cterm=NONE
  hi rustLifetime ctermfg=138 cterm=NONE
  hi rustSelf ctermfg=138 cterm=NONE
  hi rustUnsafeKeyword ctermfg=131 cterm=NONE
  hi mkdHeading ctermfg=137 cterm=NONE
  hi mkdCode ctermfg=103 cterm=NONE
  hi GitGutterAdd ctermfg=66 cterm=NONE
  hi GitGutterChange ctermfg=137 cterm=NONE
  hi GitGutterDelete ctermfg=131 cterm=NONE
  hi GitGutterChangeDelete ctermfg=240 cterm=NONE
  hi NERDTreeCWD ctermfg=60 cterm=NONE
  hi NERDTreeExecFile ctermfg=60 cterm=NONE
  hi NERDTreeOpenable ctermfg=60 cterm=NONE
  hi NERDTreeClosable ctermfg=247 cterm=NONE
  hi NERDTreeFile ctermfg=247 cterm=NONE
  hi NERDTreeDir ctermfg=247 cterm=NONE
  hi NERDTreeDirSlash ctermfg=247 cterm=NONE
  hi SignatureMarkText ctermfg=103 cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi Type cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'suisei_transp_bg', 0) && !has('gui_running')
      hi Normal ctermfg=LightGrey ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=LightGrey ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=LightGrey ctermbg=Black cterm=NONE
      hi Terminal ctermfg=LightGrey ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermbg=DarkGrey cterm=NONE
    hi Conceal cterm=NONE
    hi Cursor ctermbg=LightGrey cterm=NONE
    hi CursorColumn ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
    hi CursorLine ctermbg=Grey cterm=NONE
    hi CursorLineNr ctermfg=DarkYellow ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=DarkGreen cterm=NONE
    hi DiffChange ctermfg=DarkYellow cterm=NONE
    hi DiffDelete ctermfg=DarkRed cterm=NONE
    hi DiffText ctermfg=LightGrey cterm=NONE
    hi Directory ctermfg=Grey cterm=NONE
    if get(g:, 'suisei_hide_end_of_buffer', 0)
      hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
    else
      hi EndOfBuffer ctermfg=DarkGrey ctermbg=Black cterm=NONE
    endif
    hi ErrorMsg ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=Grey ctermbg=Black cterm=NONE
    hi Folded ctermfg=Grey ctermbg=Black cterm=NONE
    hi IncSearch cterm=reverse
    hi LineNr ctermfg=Grey ctermbg=NONE cterm=NONE
    hi MatchParen ctermbg=NONE cterm=underline
    hi ModeMsg ctermfg=LightGrey cterm=NONE
    hi MoreMsg ctermfg=LightGrey cterm=NONE
    hi NonText ctermfg=DarkGrey cterm=NONE
    hi Pmenu ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
    hi PmenuSbar ctermbg=DarkGrey cterm=NONE
    hi PmenuSel ctermfg=LightGrey ctermbg=Grey cterm=NONE
    hi PmenuThumb ctermbg=Grey cterm=NONE
    hi Question ctermfg=LightGrey cterm=NONE
    hi Search ctermfg=LightGrey ctermbg=Grey cterm=NONE
    hi SignColumn ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=DarkGrey ctermbg=Black cterm=NONE
    hi Whitespace ctermfg=DarkGrey ctermbg=Black cterm=NONE
    hi SpellBad ctermfg=LightRed cterm=underline
    hi SpellCap ctermfg=LightMagenta cterm=underline
    hi SpellLocal ctermfg=LightCyan cterm=underline
    hi SpellRare ctermfg=Grey cterm=underline
    if get(g:, 'suisei_hide_statusline', 0)
      hi StatusLine ctermfg=LightGrey ctermbg=Black cterm=NONE
      hi StatusLineNC ctermfg=LightGrey ctermbg=Black cterm=NONE
    else
      hi StatusLine ctermfg=Black ctermbg=Black cterm=NONE
      hi StatusLineNC ctermfg=Black ctermbg=Black cterm=NONE
    endif
    hi TabLine ctermfg=LightGrey ctermbg=Black cterm=NONE
    hi TabLineFill ctermbg=DarkGrey cterm=NONE
    hi TabLineSel ctermfg=LightGrey ctermbg=Grey cterm=NONE
    hi Title ctermfg=LightGrey cterm=NONE
    if get(g:, 'suisei_hide_vert_split', 0)
      hi VertSplit ctermfg=NONE ctermbg=DarkGrey cterm=NONE
    else
      hi VertSplit ctermfg=Black ctermbg=NONE cterm=NONE
    endif
    hi Visual ctermbg=DarkGrey cterm=NONE
    hi VisualNOS ctermbg=DarkRed cterm=NONE
    hi WarningMsg ctermfg=LightYellow ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
    hi Comment ctermfg=Grey cterm=italic
    hi Constant ctermfg=LightCyan cterm=NONE
    hi String ctermfg=DarkGreen cterm=NONE
    hi Error ctermfg=LightRed ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=LightMagenta cterm=NONE
    hi Ignore ctermfg=Grey cterm=NONE
    hi PreProc ctermfg=Grey cterm=NONE
    hi Special ctermfg=LightCyan cterm=NONE
    hi Statement ctermfg=LightBlue cterm=NONE
    hi Todo ctermfg=DarkGreen ctermbg=NONE cterm=NONE
    hi Type ctermfg=LightBlue cterm=italic
    hi Underlined ctermfg=DarkBlue cterm=underline
    hi haskellDecl ctermfg=LightYellow cterm=NONE
    hi haskellType ctermfg=LightCyan cterm=NONE
    hi haskellPragma ctermfg=LightYellow cterm=NONE
    hi rustCommentLineDoc ctermfg=Grey cterm=NONE
    hi rustAttribute ctermfg=DarkYellow cterm=NONE
    hi rustDerive ctermfg=DarkYellow cterm=NONE
    hi rustLifetime ctermfg=LightMagenta cterm=NONE
    hi rustSelf ctermfg=LightMagenta cterm=NONE
    hi rustUnsafeKeyword ctermfg=DarkRed cterm=NONE
    hi mkdHeading ctermfg=DarkYellow cterm=NONE
    hi mkdCode ctermfg=LightCyan cterm=NONE
    hi GitGutterAdd ctermfg=DarkGreen cterm=NONE
    hi GitGutterChange ctermfg=DarkYellow cterm=NONE
    hi GitGutterDelete ctermfg=DarkRed cterm=NONE
    hi GitGutterChangeDelete ctermfg=DarkMagenta cterm=NONE
    hi NERDTreeCWD ctermfg=Grey cterm=NONE
    hi NERDTreeExecFile ctermfg=DarkBlue cterm=NONE
    hi NERDTreeOpenable ctermfg=Grey cterm=NONE
    hi NERDTreeClosable ctermfg=Grey cterm=NONE
    hi NERDTreeFile ctermfg=Grey cterm=NONE
    hi NERDTreeDir ctermfg=Grey cterm=NONE
    hi NERDTreeDirSlash ctermfg=Grey cterm=NONE
    hi SignatureMarkText ctermfg=LightCyan cterm=NONE
    if !s:italics
      hi Comment cterm=NONE
      hi Type cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'suisei_transp_bg', 0) && !has('gui_running')
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi Terminal ctermfg=White ctermbg=DarkGrey cterm=NONE
  endif
  hi ColorColumn ctermbg=LightGrey cterm=NONE
  hi Conceal cterm=NONE
  hi Cursor ctermbg=White cterm=NONE
  hi CursorColumn ctermfg=White ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=DarkYellow cterm=NONE
  hi DiffDelete ctermfg=DarkRed cterm=NONE
  hi DiffText ctermfg=White cterm=NONE
  hi Directory ctermfg=Grey cterm=NONE
  if get(g:, 'suisei_hide_end_of_buffer', 0)
    hi EndOfBuffer ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  else
    hi EndOfBuffer ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  endif
  hi ErrorMsg ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi IncSearch cterm=reverse
  hi LineNr ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi MatchParen ctermbg=NONE cterm=underline
  hi ModeMsg ctermfg=White cterm=NONE
  hi MoreMsg ctermfg=White cterm=NONE
  hi NonText ctermfg=LightGrey cterm=NONE
  hi Pmenu ctermfg=White ctermbg=LightGrey cterm=NONE
  hi PmenuSbar ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermbg=LightGrey cterm=NONE
  hi Question ctermfg=White cterm=NONE
  hi Search ctermfg=White ctermbg=LightGrey cterm=NONE
  hi SignColumn ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi Whitespace ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi SpellBad ctermfg=LightRed cterm=underline
  hi SpellCap ctermfg=LightMagenta cterm=underline
  hi SpellLocal ctermfg=LightCyan cterm=underline
  hi SpellRare ctermfg=Grey cterm=underline
  if get(g:, 'suisei_hide_statusline', 0)
    hi StatusLine ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi StatusLineNC ctermfg=White ctermbg=DarkGrey cterm=NONE
  else
    hi StatusLine ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
    hi StatusLineNC ctermfg=DarkGrey ctermbg=DarkGrey cterm=NONE
  endif
  hi TabLine ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi TabLineFill ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=LightGrey cterm=NONE
  hi Title ctermfg=White cterm=NONE
  if get(g:, 'suisei_hide_vert_split', 0)
    hi VertSplit ctermfg=NONE ctermbg=LightGrey cterm=NONE
  else
    hi VertSplit ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  endif
  hi Visual ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermbg=DarkRed cterm=NONE
  hi WarningMsg ctermfg=LightYellow ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=White ctermbg=LightGrey cterm=NONE
  hi Comment ctermfg=Grey cterm=italic
  hi Constant ctermfg=LightCyan cterm=NONE
  hi String ctermfg=DarkGreen cterm=NONE
  hi Error ctermfg=LightRed ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=LightMagenta cterm=NONE
  hi Ignore ctermfg=LightGrey cterm=NONE
  hi PreProc ctermfg=Grey cterm=NONE
  hi Special ctermfg=LightCyan cterm=NONE
  hi Statement ctermfg=LightBlue cterm=NONE
  hi Todo ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Type ctermfg=LightBlue cterm=italic
  hi Underlined ctermfg=DarkBlue cterm=underline
  hi haskellDecl ctermfg=LightYellow cterm=NONE
  hi haskellType ctermfg=LightCyan cterm=NONE
  hi haskellPragma ctermfg=LightYellow cterm=NONE
  hi rustCommentLineDoc ctermfg=LightGrey cterm=NONE
  hi rustAttribute ctermfg=DarkYellow cterm=NONE
  hi rustDerive ctermfg=DarkYellow cterm=NONE
  hi rustLifetime ctermfg=LightMagenta cterm=NONE
  hi rustSelf ctermfg=LightMagenta cterm=NONE
  hi rustUnsafeKeyword ctermfg=DarkRed cterm=NONE
  hi mkdHeading ctermfg=DarkYellow cterm=NONE
  hi mkdCode ctermfg=LightCyan cterm=NONE
  hi GitGutterAdd ctermfg=DarkGreen cterm=NONE
  hi GitGutterChange ctermfg=DarkYellow cterm=NONE
  hi GitGutterDelete ctermfg=DarkRed cterm=NONE
  hi GitGutterChangeDelete ctermfg=DarkMagenta cterm=NONE
  hi NERDTreeCWD ctermfg=LightGrey cterm=NONE
  hi NERDTreeExecFile ctermfg=DarkBlue cterm=NONE
  hi NERDTreeOpenable ctermfg=LightGrey cterm=NONE
  hi NERDTreeClosable ctermfg=Grey cterm=NONE
  hi NERDTreeFile ctermfg=Grey cterm=NONE
  hi NERDTreeDir ctermfg=Grey cterm=NONE
  hi NERDTreeDirSlash ctermfg=Grey cterm=NONE
  hi SignatureMarkText ctermfg=LightCyan cterm=NONE
  if !s:italics
    hi Comment cterm=NONE
    hi Type cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: background #1D242d ~ Black
" Color: foreground #908f95 ~ LightGrey
" Color: hint1 #242b34 ~ DarkGrey
" Color: hint2 #353f4d ~ Grey
" Color: grey1 #344457 ~ Grey
" Color: grey2 #546478 ~ Grey
" Color: green1 #6aa389 ~ DarkGreen
" Color: green2 #6cad89 ~ LightGreen
" Color: blue1 #435c8a ~ DarkBlue
" Color: blue2 #4d75bd ~ LightBlue
" Color: yellow1 #ad8a5e ~ DarkYellow
" Color: yellow2 #d4a56c ~ LightYellow
" Color: purple1 #68678a ~ DarkCyan
" Color: purple2 #7d7bad ~ LightCyan
" Color: brown1 #916e6e ~ DarkMagenta
" Color: brown2 #bf7c7c ~ LightMagenta
" Color: red1 #995665 ~ DarkRed
" Color: red2 #c76d81 ~ LightRed
" Term Colors:  background  foreground  grey1    grey2
" Term Colors:  green1      green2      blue1    blue2
" Term Colors:  yellow1     yellow2     purple1  purple2
" Term Colors:  brown1      brown2      red1     red2
" Background: light
" Color:  background  #F0F0F4  ~        DarkGrey
" Color:  foreground  #102C4E  ~        White
" Color:  hint1       #E4E4E8  ~        LightGrey
" Color:  hint2       #D2D2D9  ~        LightGrey
" Color:  grey1       #676880  ~        LightGrey
" Color:  grey2       #A0A0AD  ~        Grey
" Color:  green1      #718A7D  ~        DarkGreen
" Color:  green2      #5E8D89  ~        LightGreen
" Color:  blue1       #3C5685  ~        DarkBlue
" Color:  blue2       #4969A3  ~        LightBlue
" Color:  yellow1     #BA8F4C  ~        DarkYellow
" Color:  yellow2     #D9A250  ~        LightYellow
" Color:  purple1     #565163  ~        DarkCyan
" Color:  purple2     #7C758F  ~        LightCyan
" Color:  brown1      #634F4F  ~        DarkMagenta
" Color:  brown2      #A17F7F  ~        LightMagenta
" Color:  red1        #995757  ~        DarkRed
" Color:  red2        #C47474  ~        LightRed
" Term Colors:  background  foreground  grey1    grey2
" Term Colors:  green1      green2      blue1    blue2
" Term Colors:  yellow1     yellow2     purple1  purple2
" Term Colors:  brown1      brown2      red1     red2
" Background: any
" vim: et ts=2 sw=2
