name: Test CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2

      - name: Setup NeoVim
        uses: rhysd/action-setup-vim@v1.2.3
        with:
          neovim: true

      - name: Build
        run: |
          make build
